version: "3.9"

services:
  app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521/XEPDB1
      SPRING_DATASOURCE_USERNAME: app_user
      SPRING_DATASOURCE_PASSWORD: app_password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: oracle.jdbc.OracleDriver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.OracleDialect
    depends_on:
      - oracle-db

  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      APP_USER: ${BACK_EMAIL}
      APP_USER_PASSWORD: ${BACK_PASSWORD}
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data:
