spring:
  datasource:
    url: jdbc:oracle:thin:@localhost/XEPDB1
    username: sa
    password:
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
