telegram:
  bot:
    webhook-path: /webhook

server:
  port: 8443
  ssl:
    enabled: true
    key-store: ${KEY_STORE_PATH}
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-type: ${KEY_STORE_TYPE}