spring:
  application:
    name: telegram
  datasource:
    url: jdbc:oracle:thin:@localhost/XEPDB1
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

telegram:
  bot:
    token: ${TELEGRAM_TOKEN}
    chat-id: ${TELEGRAM_CHAT_ID}
