spring:
  application:
    name: ChurnNotif
  datasource:
    url: jdbc:oracle:thin:@localhost/XEPDB1
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  flyway:
    enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${BACK_EMAIL}
    password: ${BACK_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
telegram:
  bot:
    token: ${TELEGRAM_TOKEN}
    chat-id: ${TELEGRAM_CHAT_ID}
